# Generated by Django 4.2.2 on 2023-07-07 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='picture',
            name='orientation',
            field=models.CharField(choices=[('VERTICAL', 'Vertical'), ('HORIZONTAL', 'Horizontal'), ('SQUARE', 'Quadrada')], default='', max_length=100),
        ),
    ]
